//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace di.proyecto.clase.ribbon.Backend.Modelo
{
    using di.proyecto.clase.ribbon.MVVM;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class articulo : PropertyChangedDataError {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public articulo()
        {
            this.salida = new HashSet<salida>();
            this.articulo1 = new HashSet<articulo>();
        }
    
        public int idarticulo { get; set; }
        public string numserie { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fechaalta { get; set; }
        public Nullable<System.DateTime> fechabaja { get; set; }
        public Nullable<int> usuarioalta { get; set; }
        public Nullable<int> usuariobaja { get; set; }
        public int modelo { get; set; }
        public Nullable<int> departamento { get; set; }
        public int espacio { get; set; }
        public Nullable<int> dentrode { get; set; }
        public string observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salida> salida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulo> articulo1 { get; set; }
        public virtual articulo articulo2 { get; set; }

        [Required(ErrorMessage = "Campo Departamento obligatorio")]
        public virtual departamento departamento1 { get; set; }

        [Required(ErrorMessage = "Campo Espacio obligatorio")]
        public virtual espacio espacio1 { get; set; }

        [Required(ErrorMessage = "Campo Modelo Articulo obligatorio")]
        public virtual modeloarticulo modeloarticulo { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
