//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace di.proyecto.clase.ribbon.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ficheromodelo
    {
        public int idficheromodelo { get; set; }
        public int modelo { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public byte[] contenido { get; set; }
    
        public virtual modeloarticulo modeloarticulo { get; set; }
    }
}
