//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace di.proyecto.clase.ribbon.Backend.Modelo
{
    using di.proyecto.clase.ribbon.MVVM;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class modeloarticulo : PropertyChangedDataError
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public modeloarticulo()
        {
            this.articulo = new HashSet<articulo>();
            this.ficheromodelo = new HashSet<ficheromodelo>();
        }
    
        public int idmodeloarticulo { get; set; }

        [Required(ErrorMessage = "El campo Nombre es obligatorio")]
        [MaxLength(45, ErrorMessage = "El campo no puede tener más de 45 carácteres")]
        public string nombre { get; set; }
        public string descripcion { get; set; }

        [Required(ErrorMessage ="El campo Marca es obligatorio")]
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<int> tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulo> articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ficheromodelo> ficheromodelo { get; set; }

        [Required(ErrorMessage = "El campo Tipo Modelo es obligatorio")]
        public virtual tipoarticulo tipoarticulo { get; set; }
    }
}
