//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace di.proyecto.clase.ribbon.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisosrol
    {
        public int idpermisosrol { get; set; }
        public int rol { get; set; }
        public int permiso { get; set; }
        public Nullable<int> acceso { get; set; }
    
        public virtual permiso permiso1 { get; set; }
        public virtual rol rol1 { get; set; }
    }
}
