//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace di.proyecto.clase.ribbon.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoarticulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipoarticulo()
        {
            this.modeloarticulo = new HashSet<modeloarticulo>();
            this.tipoarticulo1 = new HashSet<tipoarticulo>();
        }
    
        public int idtipoarticulo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> padre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modeloarticulo> modeloarticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipoarticulo> tipoarticulo1 { get; set; }
        public virtual tipoarticulo tipoarticulo2 { get; set; }
    }
}
